### ISSUE TITLE
src/tshx/Parser.hx:19: lines 19-558 : Class not found : hxparse.LexerTokenSource

### ISSUE THREAD

**Issue by alamboley** [Simn/ts2hx#21]
I installed:
`haxelib install hxparse`
`haxelib install hxargs`
Then run `haxe build.hxml`and get:
`src/tshx/Parser.hx:19: lines 19-558 : Class not found : hxparse.LexerTokenSource`

**Comment by Simn** [comment]
ts2hx requires the git version of hxparse at the moment.

**Comment by alamboley** [comment]
Thanks for the quick answer. I'm not really familiar with haxelib management, would you mind to add ts2hx.n to the current repository?
I'd like to generate Phaser externs https://github.com/photonstorm/phaser/tree/master/typescript

**Comment by nadako** [comment]
https://github.com/Blank101/haxe-phaser ?

**Comment by alamboley** [comment]
Unfortunately it isn't up to date and I've some issues with the build script.
