### ISSUE TITLE
Cannot type an imported member referenced by `typeof`

### ISSUE THREAD

**Issue by sledorze** [Simn/ts2hx#24]
This is both a ts2hx and a haxe issue:

I've generated some definition from rxjs (-d option of tsc compiler)
and I see that this library expand functionality of Observable by enhancing it's definition in file scope when someone does some imports of declaration that looks like this:

```
declare module "add/operator/expand" {
    import { expand } from "operator/expand";
    module "Observable" {
        interface Observable<T> {
            expand: typeof expand;
        }
    }
}
```
This one add the `expand` member to Observable with the type referenced from the import.

If we want to translate that to haxe via ts2hx (with some minor tweaks to it since it was not able to parse some typescript features), then we have the problem of defining a type based on another one.

I'm refering here to the type of the `expand` member which would take the type of the imported `expand`thing (which is actually 3 functions).

Do you think that's something that may evolve?

**Comment by Simn** [comment]
Fair warning, I'm mostly ignoring this repository and don't plan to maintain it. I can merge pull requests though, even if I probably won't review them properly.

**Comment by nadako** [comment]
We were talkinig about "advanced" TS type system things such as type queries, declaration merging and whatnot. Implementing this all in Haxe in ts2hx would be quite a waste of effort. What we could try doing instead is using the [TS compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) itself (e.g. via haxe externs) to analyze, transform and finally generate haxe type definitions...

**Comment by sledorze** [comment]
I understand your concerns @Simn and that you keep focusing :)
@nadako Hum.. that's for sure a better idea!
Maybe I'll try something when I've enough free time.
