### ISSUE TITLE
Uncaught exception - Invalid field access : length

### ISSUE THREAD

**Issue by laurence-myers** [Simn/ts2hx#9]
I tried converting the entirety of the DefinitelyTyped repo, but many definitions failed with the following exception:

    Called from ? line 1
    Called from Main.hx line 69
    Called from Main.hx line 111
    Called from Main.hx line 87
    Called from Main.hx line 101
    Called from Main.hx line 92
    Called from Main.hx line 154
    Called from E:\Apps\Programming\HaxeToolkit\haxe\std/haxe/macro/Printer.hx line
    251
    Uncaught exception - Invalid field access : length

Here is one of the simplest definitions I could find:
https://github.com/borisyankov/DefinitelyTyped/blob/master/add2home/add2home.d.ts
This is nothing more than a variable declaration, containing an object with three functions.

Another example:
https://github.com/borisyankov/DefinitelyTyped/blob/master/accounting/accounting.d.ts
This defines a variable "accounting", which then gets exported in a module.

Another example:
https://github.com/borisyankov/DefinitelyTyped/blob/master/alertify/alertify.d.ts
This defines a variable, "declare var alertify: alertify.IAlertifyStatic;", and a module. The module seems to get transpiled & written correctly, but an error is also thrown, presumably because of the variable declaration. As an experiment, I removed the variable declaration line, and then no error was thrown (though I don't know if the output was entirely correct, since it would be missing the var decl conversion).

Full output log is here:
https://gist.github.com/laurence-myers/e865cae0a1c126c49337

**Comment by Simn** [comment]
What Haxe version are you using? I'm not getting these errors (though I'm getting some others related to type choice parsing).

**Comment by laurence-myers** [comment]
Thanks for looking into this! I'm using Haxe v3.1.3, running on Windows 8.1 (x64). Here's my lib versions, according to haxelib (I've added the git changesets and dates for the dev libs):

    dox: [1.0.0]
    hxargs: [3.0.0]
    hxparse: git [dev:E:\Apps\Programming\HaxeToolkit\haxe\lib/hxparse/git/src]  <-- 169065a398d541e620ff04384423fd5b6d07aa63, 2014-06-04
    hxtemplo: git [dev:E:\Apps\Programming\HaxeToolkit\haxe\lib/hxtemplo/git/src]  <-- 47343e3a8a8a951bc7bf9206d9fd1eb4cbddbb67, 2014-07-02
    ihx: [0.3.4]
    markdown: [1.0.0-alpha]
    ts2hx: git [dev:E:\Apps\Programming\HaxeToolkit\haxe\lib/ts2hx/git]  <-- 71cd6b11f5fbfcbc3895c189357da4a83bb12422, 2015-03-08

This is the command I ran to build and execute ts2hx:

    haxe build.hxml
    neko run.n "F:\\Code\\Other\\DefinitelyTyped" --recursive --ignore-errors --in "\.d\.ts$"

(Sorry if I haven't got something quite right, I'm a Haxe newbie.)

**Comment by Simn** [comment]
I'm surprised that compiles at all. The git version of hxparse should require the git version of Haxe.

Did you try running it without building run.n first? There's a run.n in the repository already which should be working (at least past the point you're having issues with).

**Comment by Simn** [comment]
I have updated run.n again for good measure. Running it on latest DefinitelyTyped I get all the way to this error:

```
Written out/zip.js/Zip.hx

Error Report:

File "C:\\Github\\DefinitelyTyped/archy/archy.d.ts": archy:13:characters 26-27: Unexpected { def => TPipe, pos => archy:characters 501-502 }
```

Which is the parser error I mentioned earlier which I have to address.

**Comment by laurence-myers** [comment]
Ah yes, running "run.n" without compiling it works a lot better, I now get the same error you mention.

My hxparse is quite old (2014-06-04), I assume I need the latest hxparse from Git, which in turn needs the latest Haxe from Git? I'll try that when I next recompile.

**Comment by Simn** [comment]
Note that we'll be making a Haxe release this weekend which entails haxelib releases for all my libraries. I would appreciate some more testing before that anyway!

**Comment by Simn** [comment]
I've made some parser updates so DefinitelyTyped can now almost be parsed. I'm still getting two errors because the .d.ts files have weird bytes representing spaces there.

**Comment by Simn** [comment]
All good now!

**Comment by laurence-myers** [comment]
Thanks again Simon, I really appreciate it. :)
